version: '3.2'
services:
  cypress:
    # image: 'cypress/included:9.2.0'
    # image: 'cypress/included:3.4.0'
    image: 'cypress/included:9.7.0'
    entrypoint: cypress
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
    working_dir: /cypress_example_docker_1
    volumes: 
     - ./:/cypress_example_docker_1      
