version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 3306:3306
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  # nginx:
  #   environment:
  #     VIRTUAL_HOST: ${DOMAIN_NAME}
  #     LETSENCRYPT_HOST: ${DOMAIN_NAME}

networks:
  default:
    external:
      name: proxy